AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for 
  convert desimal to raman.Website will be deployed on Amazon Linux 2 (ami-02e136e904f3da870) 
  EC2 Instance with custom security group which allows http connections
   on port 80 and ssh port 22 from anywhere.  Website 
  is downloaded from my Public Github repository, then deployed on Apache Web Server.
Parameters:
  myKP:
    Description: Select key pair
    Type: AWS::EC2::KeyPair::KeyName

  myVPC:
    Description: Please select VPC
    Type: AWS::EC2::VPC::Id

  myIT:
    Description: Select the instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t2.nano
      - t3.nano


Mappings:
  RegionImageMap: 
    us-east-1:
      AMI: ami-0dc2d3e4c0f9ebd18
    us-east-2:
      AMI: ami-0233c2d874b811deb
    us-west-1:
      AMI: ami-0ed05376b59b90e46
    us-west-2:
      AMI: ami-0dc8f589abe99f538
    eu-west-1:
      AMI: ami-058b1b7fe545997ae



Resources:
  mySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "80 and 22 ports opened" # Required
      GroupName: SG-romen
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          ToPort: 22
          FromPort: 22
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          ToPort: 80
          FromPort: 80
          IpProtocol: tcp
      VpcId: !Ref myVPC
  
  myEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
         - RegionImageMap
         - !Ref AWS::Region
         - AMI
      InstanceType: !Ref myIT
      KeyName: !Ref myKP
      SecurityGroupIds:
          - !GetAtt mySG.GroupId
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install git -y
        sudo pip3 install flask 
        git clone https://github.com/sametustaoglu/my-projects.git
        cd /home/ec2-user
        mkdir proje
        cd proje
        sudo cp -r /my-projects/aws/projects/Project-001-Roman-Numerals-Converter/* /home/ec2-user/proje
        sudo python3 app.py
        
Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt myEC2.PublicDnsName