AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      
      ImageId: ami-02e136e904f3da870
      
      InstanceType: t2.micro
      
      KeyName: key
      
      SecurityGroups:
        - launch-wizard-3
      Tags:
        - Key: Name
          Value: WebServerofStackName
     
      UserData: 
        !Base64 |
        #! /bin/bash
        #update os
        yum update -y
        #install apache server
        yum install -y httpd
        systemctl start httpd
        systemctl enable httpd
        # get date and time of server
        DATE_TIME=`date`
        # create a custom index.html file
        echo "<html>
        <head>
            <title> My First Web Server</title>
        </head>
        <body>
            <h1>Hello to Everyone from My First Web Server</h1>
            <p>This instance is created at <b>$DATE_TIME</b></p>
        </body>
        </html>" > /var/www/html/index.html
        # start apache server
        systemctl start httpd
        systemctl enable httpd
        
        
        
      
