AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      
      ImageId: ami-02e136e904f3da870
      
      InstanceType: t2.micro
      
      KeyName: key
      
      SecurityGroups:
        - !Ref SG
      Tags:
        - Key: Name
          Value: WebServerofStackName
     
      UserData: 
        !Base64 |
        #!/bin/bash
        #update os
        yum update -y
        #install git
        yum install git -y
        #install apache server
        sudo yum install -y httpd
        systemctl start httpd
        systemctl enable httpd
        git clone https://github.com/sametustaoglu/my-projects.git
        sudo cp /my-projects/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web/* /var/www/html

  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sg icin # Required
      GroupName: sg
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        

        
      
     
        
      
        
        
      
